server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/shop_xcx
    username: root
    password: 123456789


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

weixin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wx062eb8e0bada2b9f
  secret: 1d68788e0dd2fec37065e41af173ddaa

bigTypeImagesFilePath: D://项目/购物小程序/图片/bigTypeImgs/
productImagesFilePath: D://项目/购物小程序/图片/productImgs/
swiperImagesFilePath: D://项目/购物小程序/图片/swiperImgs/
productSwiperImagesFilePath: D://项目/购物小程序/图片/productSwiperImgs/
#weixinpayconfig:
#  appid: #
#  mch_id:
#  key:
#  url:
#  notify_url: